image: Visual Studio 2017

install:
- cmd: appveyor downloadfile https://dist.nuget.org/win-x86-commandline/v4.3.0/nuget.exe

before_build:
- cmd: nuget restore

build:
  project: Thrifty.sln
  verbosity: normal

test_script:
  - cmd: dotnet run -c Release -p src\tests\Thrifty.UnitTests\Thrifty.UnitTests.csproj

test: off